// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DummyMessage.proto

// Protobuf Java Version: 3.25.3
package pl.perfluencer.kafka.proto;

public interface DummyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pl.perfluencer.kafka.proto.DummyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_id = 1;</code>
   * @return The responseId.
   */
  java.lang.String getResponseId();
  /**
   * <code>string response_id = 1;</code>
   * @return The bytes for responseId.
   */
  com.google.protobuf.ByteString
      getResponseIdBytes();

  /**
   * <pre>
   * To correlate with the request
   * </pre>
   *
   * <code>string request_id_echo = 2;</code>
   * @return The requestIdEcho.
   */
  java.lang.String getRequestIdEcho();
  /**
   * <pre>
   * To correlate with the request
   * </pre>
   *
   * <code>string request_id_echo = 2;</code>
   * @return The bytes for requestIdEcho.
   */
  com.google.protobuf.ByteString
      getRequestIdEchoBytes();

  /**
   * <code>string response_payload = 3;</code>
   * @return The responsePayload.
   */
  java.lang.String getResponsePayload();
  /**
   * <code>string response_payload = 3;</code>
   * @return The bytes for responsePayload.
   */
  com.google.protobuf.ByteString
      getResponsePayloadBytes();

  /**
   * <code>bool success = 4;</code>
   * @return The success.
   */
  boolean getSuccess();
}
