
drop table requests;
CREATE TABLE requests(
    correlation_id uuid NOT NULL,
    request_key text,
    request_value_bytes bytea,
    serialization_type varchar(50) NOT NULL,
    transaction_name varchar(255) NOT NULL,
    start_time timestamp with time zone NOT NULL,
    expired boolean NOT NULL DEFAULT false,
    PRIMARY KEY(correlation_id)
) PARTITION BY HASH(correlation_id);


CREATE TABLE requests_p0 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 0);

CREATE TABLE requests_p1 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 1);

CREATE TABLE requests_p2 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 2);

CREATE TABLE requests_p3 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 3);

CREATE TABLE requests_p4 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 4);

CREATE TABLE requests_p5 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 5);

CREATE TABLE requests_p6 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 6);

CREATE TABLE requests_p7 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 7);

CREATE TABLE requests_p8 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 8);

CREATE TABLE requests_p9 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 9);

CREATE TABLE requests_p10 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 10);

CREATE TABLE requests_p11 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 11);

CREATE TABLE requests_p12 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 12);

CREATE TABLE requests_p13 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 13);

CREATE TABLE requests_p14 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 14);

CREATE TABLE requests_p15 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 15);

CREATE TABLE requests_p16 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 16);

CREATE TABLE requests_p17 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 17);

CREATE TABLE requests_p18 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 18);

CREATE TABLE requests_p19 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 19);

CREATE TABLE requests_p20 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 20);

CREATE TABLE requests_p21 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 21);

CREATE TABLE requests_p22 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 22);

CREATE TABLE requests_p23 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 23);

CREATE TABLE requests_p24 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 24);

CREATE TABLE requests_p25 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 25);

CREATE TABLE requests_p26 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 26);

CREATE TABLE requests_p27 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 27);

CREATE TABLE requests_p28 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 28);

CREATE TABLE requests_p29 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 29);

CREATE TABLE requests_p30 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 30);

CREATE TABLE requests_p31 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 31);

CREATE TABLE requests_p32 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 32);

CREATE TABLE requests_p33 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 33);

CREATE TABLE requests_p34 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 34);

CREATE TABLE requests_p35 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 35);

CREATE TABLE requests_p36 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 36);

CREATE TABLE requests_p37 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 37);

CREATE TABLE requests_p38 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 38);

CREATE TABLE requests_p39 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 39);

CREATE TABLE requests_p40 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 40);

CREATE TABLE requests_p41 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 41);

CREATE TABLE requests_p42 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 42);

CREATE TABLE requests_p43 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 43);

CREATE TABLE requests_p44 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 44);

CREATE TABLE requests_p45 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 45);

CREATE TABLE requests_p46 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 46);

CREATE TABLE requests_p47 PARTITION OF requests
    FOR VALUES WITH (MODULUS 48, REMAINDER 47);