// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DummyMessage.proto

// Protobuf Java Version: 3.25.3
package pl.perfluencer.kafka.proto;

public final class DummyMessage {
  private DummyMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_perfluencer_kafka_proto_DummyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_perfluencer_kafka_proto_DummyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pl_perfluencer_kafka_proto_DummyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pl_perfluencer_kafka_proto_DummyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DummyMessage.proto\022\032pl.perfluencer.kaf" +
      "ka.proto\";\n\014DummyRequest\022\022\n\nrequest_id\030\001" +
      " \001(\t\022\027\n\017request_payload\030\002 \001(\t\"h\n\rDummyRe" +
      "sponse\022\023\n\013response_id\030\001 \001(\t\022\027\n\017request_i" +
      "d_echo\030\002 \001(\t\022\030\n\020response_payload\030\003 \001(\t\022\017" +
      "\n\007success\030\004 \001(\010B\036\n\032pl.perfluencer.kafka." +
      "protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pl_perfluencer_kafka_proto_DummyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pl_perfluencer_kafka_proto_DummyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_perfluencer_kafka_proto_DummyRequest_descriptor,
        new java.lang.String[] { "RequestId", "RequestPayload", });
    internal_static_pl_perfluencer_kafka_proto_DummyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pl_perfluencer_kafka_proto_DummyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pl_perfluencer_kafka_proto_DummyResponse_descriptor,
        new java.lang.String[] { "ResponseId", "RequestIdEcho", "ResponsePayload", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
