// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/test/java/io/github/kbdering/kafka/proto/DummyMessage.proto
// Protobuf Java Version: 4.29.3

package io.github.kbdering.kafka.proto;

/**
 * Protobuf type {@code io.github.kbdering.kafka.proto.DummyResponse}
 */
public final class DummyResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.kbdering.kafka.proto.DummyResponse)
    DummyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      DummyResponse.class.getName());
  }
  // Use DummyResponse.newBuilder() to construct.
  private DummyResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DummyResponse() {
    responseId_ = "";
    requestIdEcho_ = "";
    responsePayload_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.kbdering.kafka.proto.DummyMessage.internal_static_io_github_kbdering_kafka_proto_DummyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.kbdering.kafka.proto.DummyMessage.internal_static_io_github_kbdering_kafka_proto_DummyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.kbdering.kafka.proto.DummyResponse.class, io.github.kbdering.kafka.proto.DummyResponse.Builder.class);
  }

  public static final int RESPONSE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object responseId_ = "";
  /**
   * <code>string response_id = 1;</code>
   * @return The responseId.
   */
  @java.lang.Override
  public java.lang.String getResponseId() {
    java.lang.Object ref = responseId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseId_ = s;
      return s;
    }
  }
  /**
   * <code>string response_id = 1;</code>
   * @return The bytes for responseId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseIdBytes() {
    java.lang.Object ref = responseId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REQUEST_ID_ECHO_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object requestIdEcho_ = "";
  /**
   * <pre>
   * To correlate with the request
   * </pre>
   *
   * <code>string request_id_echo = 2;</code>
   * @return The requestIdEcho.
   */
  @java.lang.Override
  public java.lang.String getRequestIdEcho() {
    java.lang.Object ref = requestIdEcho_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      requestIdEcho_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * To correlate with the request
   * </pre>
   *
   * <code>string request_id_echo = 2;</code>
   * @return The bytes for requestIdEcho.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRequestIdEchoBytes() {
    java.lang.Object ref = requestIdEcho_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      requestIdEcho_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_PAYLOAD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object responsePayload_ = "";
  /**
   * <code>string response_payload = 3;</code>
   * @return The responsePayload.
   */
  @java.lang.Override
  public java.lang.String getResponsePayload() {
    java.lang.Object ref = responsePayload_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responsePayload_ = s;
      return s;
    }
  }
  /**
   * <code>string response_payload = 3;</code>
   * @return The bytes for responsePayload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponsePayloadBytes() {
    java.lang.Object ref = responsePayload_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responsePayload_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESS_FIELD_NUMBER = 4;
  private boolean success_ = false;
  /**
   * <code>bool success = 4;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, responseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestIdEcho_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, requestIdEcho_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responsePayload_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, responsePayload_);
    }
    if (success_ != false) {
      output.writeBool(4, success_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responseId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, responseId_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(requestIdEcho_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requestIdEcho_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(responsePayload_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, responsePayload_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, success_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.kbdering.kafka.proto.DummyResponse)) {
      return super.equals(obj);
    }
    io.github.kbdering.kafka.proto.DummyResponse other = (io.github.kbdering.kafka.proto.DummyResponse) obj;

    if (!getResponseId()
        .equals(other.getResponseId())) return false;
    if (!getRequestIdEcho()
        .equals(other.getRequestIdEcho())) return false;
    if (!getResponsePayload()
        .equals(other.getResponsePayload())) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RESPONSE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getResponseId().hashCode();
    hash = (37 * hash) + REQUEST_ID_ECHO_FIELD_NUMBER;
    hash = (53 * hash) + getRequestIdEcho().hashCode();
    hash = (37 * hash) + RESPONSE_PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getResponsePayload().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.kbdering.kafka.proto.DummyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.kbdering.kafka.proto.DummyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.kbdering.kafka.proto.DummyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.kbdering.kafka.proto.DummyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.kbdering.kafka.proto.DummyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.kbdering.kafka.proto.DummyResponse)
      io.github.kbdering.kafka.proto.DummyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.kbdering.kafka.proto.DummyMessage.internal_static_io_github_kbdering_kafka_proto_DummyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.kbdering.kafka.proto.DummyMessage.internal_static_io_github_kbdering_kafka_proto_DummyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.kbdering.kafka.proto.DummyResponse.class, io.github.kbdering.kafka.proto.DummyResponse.Builder.class);
    }

    // Construct using io.github.kbdering.kafka.proto.DummyResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      responseId_ = "";
      requestIdEcho_ = "";
      responsePayload_ = "";
      success_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.kbdering.kafka.proto.DummyMessage.internal_static_io_github_kbdering_kafka_proto_DummyResponse_descriptor;
    }

    @java.lang.Override
    public io.github.kbdering.kafka.proto.DummyResponse getDefaultInstanceForType() {
      return io.github.kbdering.kafka.proto.DummyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.kbdering.kafka.proto.DummyResponse build() {
      io.github.kbdering.kafka.proto.DummyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.kbdering.kafka.proto.DummyResponse buildPartial() {
      io.github.kbdering.kafka.proto.DummyResponse result = new io.github.kbdering.kafka.proto.DummyResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.kbdering.kafka.proto.DummyResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.responseId_ = responseId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.requestIdEcho_ = requestIdEcho_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.responsePayload_ = responsePayload_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.success_ = success_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.kbdering.kafka.proto.DummyResponse) {
        return mergeFrom((io.github.kbdering.kafka.proto.DummyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.kbdering.kafka.proto.DummyResponse other) {
      if (other == io.github.kbdering.kafka.proto.DummyResponse.getDefaultInstance()) return this;
      if (!other.getResponseId().isEmpty()) {
        responseId_ = other.responseId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRequestIdEcho().isEmpty()) {
        requestIdEcho_ = other.requestIdEcho_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getResponsePayload().isEmpty()) {
        responsePayload_ = other.responsePayload_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              responseId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              requestIdEcho_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              responsePayload_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              success_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object responseId_ = "";
    /**
     * <code>string response_id = 1;</code>
     * @return The responseId.
     */
    public java.lang.String getResponseId() {
      java.lang.Object ref = responseId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string response_id = 1;</code>
     * @return The bytes for responseId.
     */
    public com.google.protobuf.ByteString
        getResponseIdBytes() {
      java.lang.Object ref = responseId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string response_id = 1;</code>
     * @param value The responseId to set.
     * @return This builder for chaining.
     */
    public Builder setResponseId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      responseId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string response_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseId() {
      responseId_ = getDefaultInstance().getResponseId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string response_id = 1;</code>
     * @param value The bytes for responseId to set.
     * @return This builder for chaining.
     */
    public Builder setResponseIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responseId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object requestIdEcho_ = "";
    /**
     * <pre>
     * To correlate with the request
     * </pre>
     *
     * <code>string request_id_echo = 2;</code>
     * @return The requestIdEcho.
     */
    public java.lang.String getRequestIdEcho() {
      java.lang.Object ref = requestIdEcho_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestIdEcho_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * To correlate with the request
     * </pre>
     *
     * <code>string request_id_echo = 2;</code>
     * @return The bytes for requestIdEcho.
     */
    public com.google.protobuf.ByteString
        getRequestIdEchoBytes() {
      java.lang.Object ref = requestIdEcho_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestIdEcho_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * To correlate with the request
     * </pre>
     *
     * <code>string request_id_echo = 2;</code>
     * @param value The requestIdEcho to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdEcho(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      requestIdEcho_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * To correlate with the request
     * </pre>
     *
     * <code>string request_id_echo = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestIdEcho() {
      requestIdEcho_ = getDefaultInstance().getRequestIdEcho();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * To correlate with the request
     * </pre>
     *
     * <code>string request_id_echo = 2;</code>
     * @param value The bytes for requestIdEcho to set.
     * @return This builder for chaining.
     */
    public Builder setRequestIdEchoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      requestIdEcho_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object responsePayload_ = "";
    /**
     * <code>string response_payload = 3;</code>
     * @return The responsePayload.
     */
    public java.lang.String getResponsePayload() {
      java.lang.Object ref = responsePayload_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responsePayload_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string response_payload = 3;</code>
     * @return The bytes for responsePayload.
     */
    public com.google.protobuf.ByteString
        getResponsePayloadBytes() {
      java.lang.Object ref = responsePayload_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responsePayload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string response_payload = 3;</code>
     * @param value The responsePayload to set.
     * @return This builder for chaining.
     */
    public Builder setResponsePayload(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      responsePayload_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string response_payload = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponsePayload() {
      responsePayload_ = getDefaultInstance().getResponsePayload();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string response_payload = 3;</code>
     * @param value The bytes for responsePayload to set.
     * @return This builder for chaining.
     */
    public Builder setResponsePayloadBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responsePayload_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 4;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 4;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {

      success_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      bitField0_ = (bitField0_ & ~0x00000008);
      success_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.kbdering.kafka.proto.DummyResponse)
  }

  // @@protoc_insertion_point(class_scope:io.github.kbdering.kafka.proto.DummyResponse)
  private static final io.github.kbdering.kafka.proto.DummyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.kbdering.kafka.proto.DummyResponse();
  }

  public static io.github.kbdering.kafka.proto.DummyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DummyResponse>
      PARSER = new com.google.protobuf.AbstractParser<DummyResponse>() {
    @java.lang.Override
    public DummyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DummyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DummyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.kbdering.kafka.proto.DummyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

