// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/test/java/io/github/kbdering/kafka/proto/DummyMessage.proto
// Protobuf Java Version: 4.29.3

package io.github.kbdering.kafka.proto;

public interface DummyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.kbdering.kafka.proto.DummyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request_id = 1;</code>
   * @return The requestId.
   */
  java.lang.String getRequestId();
  /**
   * <code>string request_id = 1;</code>
   * @return The bytes for requestId.
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();

  /**
   * <code>string request_payload = 2;</code>
   * @return The requestPayload.
   */
  java.lang.String getRequestPayload();
  /**
   * <code>string request_payload = 2;</code>
   * @return The bytes for requestPayload.
   */
  com.google.protobuf.ByteString
      getRequestPayloadBytes();
}
