// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/test/java/io/github/kbdering/kafka/proto/DummyMessage.proto
// Protobuf Java Version: 4.29.3

package io.github.kbdering.kafka.proto;

public final class DummyMessage {
  private DummyMessage() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      DummyMessage.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_kbdering_kafka_proto_DummyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_kbdering_kafka_proto_DummyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_kbdering_kafka_proto_DummyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_kbdering_kafka_proto_DummyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?src/test/java/io/github/kbdering/kafka" +
      "/proto/DummyMessage.proto\022\036io.github.kbd" +
      "ering.kafka.proto\";\n\014DummyRequest\022\022\n\nreq" +
      "uest_id\030\001 \001(\t\022\027\n\017request_payload\030\002 \001(\t\"h" +
      "\n\rDummyResponse\022\023\n\013response_id\030\001 \001(\t\022\027\n\017" +
      "request_id_echo\030\002 \001(\t\022\030\n\020response_payloa" +
      "d\030\003 \001(\t\022\017\n\007success\030\004 \001(\010B\"\n\036io.github.kb" +
      "dering.kafka.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_kbdering_kafka_proto_DummyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_github_kbdering_kafka_proto_DummyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_kbdering_kafka_proto_DummyRequest_descriptor,
        new java.lang.String[] { "RequestId", "RequestPayload", });
    internal_static_io_github_kbdering_kafka_proto_DummyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_github_kbdering_kafka_proto_DummyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_kbdering_kafka_proto_DummyResponse_descriptor,
        new java.lang.String[] { "ResponseId", "RequestIdEcho", "ResponsePayload", "Success", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
